---
title: "SOCI 133 Fall 2020 - Class Research"
output: 
  flexdashboard::flex_dashboard:
  orientation: columns---
---

<style>
.colored {
  background-color: #e4e2d8;
}
</style>

```{r setup, include=FALSE}
library(tidyverse)
library(crosstalk)
library(flexdashboard)
library(plotly)
library(leaflet)
library(numform)
library(USAboundaries)
library(gridExtra)
library(ggmap)
library(DT)
library(knitr)
library(tigris)
library(devtools)
library(rappdirs)
library(leaflet)
library(htmlwidgets)
library(sp)
library(dplyr)
library(rgeos)
library(rgdal)
library(maptools)
library(sf)
library(spdep)
library(mapview)
library(USAboundariesData)

```


Your Research Here (1883-1941) {data-icon="fa-map"}
===========================================================


```{r}

dot_data <- read.csv("https://davidrigbysociology.s3.amazonaws.com/lynching_data/make_dot_map_with_this_03.csv", colClasses='character', stringsAsFactors=F)
dot_data$verified <- as.numeric(dot_data$verified)
dot_data$verified <- replace_na(dot_data$verified)

dot_data$county[dot_data$caseid=="5710"] <- "NEW YORK"
dot_data$GEOID[dot_data$caseid=="5710"] <- "36061"

sl <- unique(dot_data$state_fips)

invisible(capture.output(us_county_shape <- counties(sl, cb = TRUE, year = NULL)))
cds <- coordinates(us_county_shape)
dot_coords <- cbind(as.data.frame(cds) %>% setNames(c("long","lat")),us_county_shape@data['GEOID'])
county_merge <- sp::merge(us_county_shape,dot_coords, by = "GEOID")
dot_merged <- sp::merge(county_merge, dot_data, by = "GEOID", duplicateGeoms = TRUE)

invisible(capture.output(us_county_small <- us_county_shape))
invisible(capture.output(us_county_small@data <- us_county_small@data[1]))

color_race <- c("White" = "#1e3f9d", "Black" = "#D4820F", "Chinese" = "#8d371b", "Japanese" = "#5134a6", "Mexican" = "#146c2a", "American Indian" = "#1e9d7e", "Unknown" = "grey")

lynchings <- dplyr::filter(dot_merged@data, verified==1)
lynchings$colors <- color_race[lynchings$race_count]
lynchings$long_jit <- jitter(lynchings$long, factor = 80)
lynchings$lat_jit <- jitter(lynchings$lat, factor = 80)
lynchings$year <- as.Date(lynchings$year, '%Y')

lynchings$gender[lynchings$gender=="Male (?)"] <- "Male"

columns <- c("GEOID", "year", "county", "state", "victim_name", "gender", "race_count",
         "alleged_offense", "lynch_method", "vic_detes", "colors", "long_jit", "lat_jit")

lynching <- lynchings[columns]

lynch_share <- SharedData$new(lynching)

popup <- paste0("<B>County: ",lynch_share$data()$county, " - </B>", lynch_share$data()$vic_detes)
share_dot_map <- lynch_share %>%
  leaflet() %>%
  addProviderTiles("CartoDB.Positron") %>%
  
  addPolylines(data =us_county_shape,                  
               stroke = TRUE,
               weight = .5,
               color="grey") %>%
  
  addCircleMarkers(lng = lynch_share$data()$long_jit, lat = lynch_share$data()$lat_jit, weight=7, opacity = .1,     radius =1.5,color=lynch_share$data()$colors, stroke = TRUE, fillOpacity = .6, popup = popup) %>%

addLegend( 
  colors =  color_race,
  opacity=.5,
  labels = names(color_race),
  position = "bottomright", 
  title = "Race/Nationality of Victim") 

centered_dot <- setView(share_dot_map, lat = 39, lng = -97, zoom = 5)
#centered_dot

lynch_table <- datatable(lynch_share, extensions="Scroller", style="bootstrap", class="compact", width="100%", options=list(deferRender=TRUE, scrollY=300, scroller=TRUE))
```


Sidebar2 {.sidebar}
-----------------------------------------------------------------------

```{r}
filter_slider("year", "Year", lynch_share, column=~`year`, step=1, timeFormat = "%Y", animate = FALSE)
filter_checkbox("race_count", "Race of Victim", lynch_share, ~`race_count`, inline = FALSE)
filter_checkbox("gender", "Gender of Victim", lynch_share, ~`gender`, inline = TRUE)
filter_checkbox("state", "State", lynch_share, ~`state`, inline = FALSE, columns = 4)
```


Column
-----------------

###

```{r}
centered_dot
```

More Student Research {data-icon="fa-map"}
===========================================================

```{r, include=FALSE}

slave <- read.csv("https://davidrigbysociology.s3.amazonaws.com/lynching_data/1860_slave_pop.csv", stringsAsFactors=F)
slave$fips <- sprintf("%05d", slave$fips)
slave$stot <- as.numeric(slave$stot)
slave$slave_prop <- as.numeric(slave$slave_prop)
dot_data <- read.csv("https://davidrigbysociology.s3.amazonaws.com/lynching_data/make_dot_map_with_this_03.csv", colClasses='character', stringsAsFactors=F)
datatable(head(dot_data))
sapply(dot_data,class)
dot_data$verified <- as.numeric(dot_data$verified)
dot_data$verified <-replace_na(dot_data$verified)



black_dot_data <- subset(dot_data, race_count == "Black")

options(tigris_use_cache = TRUE)


us_county_shape <- counties(state = NULL, cb = TRUE, year = NULL)
cds <- coordinates(us_county_shape)
dot_coords <- cbind(as.data.frame(cds) %>% setNames(c("long","lat")),us_county_shape@data['GEOID'])
county_merge <- sp::merge(us_county_shape,dot_coords, by = "GEOID")
dot_merged <- sp::merge(county_merge, black_dot_data, by = "GEOID", duplicateGeoms = TRUE)

color_race <- c("Black" = "#D4820F")

lynchings <- dplyr::filter(dot_merged@data, verified==1)
lynchings$colors <- color_race[lynchings$race_count]
lynchings$long_jit <- jitter(lynchings$long, factor = 80)
lynchings$lat_jit <- jitter(lynchings$lat, factor = 80)

slave_shape <- us_counties(map_date = "1860-12-30",
                               resolution = "high")

slave_merge <- sp::merge(slave_shape, slave, by = "fips", duplicateGeoms = TRUE, all.x=TRUE)

### % Slave Proportion
cutpoints <- c(0, quantile(slave$slave_prop, 0.20, na.rm=TRUE), quantile(slave$slave_prop, 0.40, na.rm=TRUE), 
               quantile(slave$slave_prop, 0.60, na.rm=TRUE), quantile(slave$slave_prop, 0.80, na.rm=TRUE),
               quantile(slave$slave_prop, 0.90, na.rm=TRUE), quantile(slave$slave_prop, 1.0, na.rm=TRUE))
cutpoints

cat_list <- c("0", 				
              "0-0.0631", 		
              "0.06311-0.1666", 	
              "0.16661-0.3221", 	
              "0.32211-0.4957", 	
              "0.49571-0.601", 	
              "0.6011-0.925")
cat_list[4]

### ENTER slavebin values into 1860 shape file for old jurisdictions missinf fips
slave_merge$propbin[slave_merge$full_name == "Horry District" & slave_merge$state_name == "South Carolina"] <- cat_list[4]
slave_merge$propbin[slave_merge$full_name == "Prince Frederick Parish (superseded)" & slave_merge$state_name == "South Carolina"] <- cat_list[6]
slave_merge$propbin[slave_merge$full_name == "St. Mark Parish (superseded)" & slave_merge$state_name == "South Carolina"] <- cat_list[5]
slave_merge$propbin[slave_merge$full_name == "Georgetown District" & slave_merge$state_name == "South Carolina"] <- cat_list[6]
slave_merge$propbin[slave_merge$full_name == "St. James-Santee Parish (superseded)" & slave_merge$state_name == "South Carolina"] <- cat_list[5]
slave_merge$propbin[slave_merge$full_name == "Christ Church Parish (superseded)" & slave_merge$state_name == "South Carolina"] <- cat_list[5]
slave_merge$propbin[slave_merge$full_name == "St. Philip Parish (superseded" & slave_merge$state_name == "South Carolina"] <- cat_list[5]
slave_merge$propbin[slave_merge$full_name == "St. Andrew Parish (superseded)" & slave_merge$state_name == "South Carolina"] <- cat_list[5]
slave_merge$propbin[slave_merge$full_name == "St. John-Colleton Parish (superseded)" & slave_merge$state_name == "South Carolina"] <- cat_list[5]
slave_merge$propbin[slave_merge$full_name == "St. Stephen Parish (superseded)" & slave_merge$state_name == "South Carolina"] <- cat_list[6]
slave_merge$propbin[slave_merge$full_name == "St. John-Berkeley Parish (superseded)" & slave_merge$state_name == "South Carolina"] <- cat_list[6]
slave_merge$propbin[slave_merge$full_name == "St. James-Goose Creek Parish (superseded)" & slave_merge$state_name == "South Carolina"] <- cat_list[6]
slave_merge$propbin[slave_merge$full_name == "St. Thomas / St. Dennis Parishes (superseded)" & slave_merge$state_name == "South Carolina"] <- cat_list[6] 
slave_merge$propbin[slave_merge$full_name == "St. George-Dorchester Parish (superseded)" & slave_merge$state_name == "South Carolina"] <- cat_list[6]
slave_merge$propbin[slave_merge$full_name == "St. Bartholomew Parish (superseded)" & slave_merge$state_name == "South Carolina"] <- cat_list[6] 
slave_merge$propbin[slave_merge$full_name == "St. Helena Parish (superseded)" & slave_merge$state_name == "South Carolina"] <- cat_list[6]
slave_merge$propbin[slave_merge$full_name == "St. Luke Parish (superseded)" & slave_merge$state_name == "South Carolina"] <- cat_list[6]
slave_merge$propbin[slave_merge$full_name == "St. Peter Parish (superseded)" & slave_merge$state_name == "South Carolina"] <- cat_list[6]
slave_merge$propbin[slave_merge$full_name == "St. Paul Parish (superseded)" & slave_merge$state_name == "South Carolina"] <- cat_list[5]
slave_merge$propbin[slave_merge$full_name == "Prince William Parish (superseded)" & slave_merge$state_name == "South Carolina"] <- cat_list[6]
slave_merge$propbin[slave_merge$full_name == "Lexington District" & slave_merge$state_name == "South Carolina"] <- cat_list[5]
slave_merge$propbin[slave_merge$full_name == "Orangeburg District" & slave_merge$state_name == "South Carolina"] <- cat_list[6]
slave_merge$propbin[slave_merge$full_name == "Barnwell District" & slave_merge$state_name == "South Carolina"] <- cat_list[6]
slave_merge$propbin[slave_merge$full_name == "Williamsburg District" & slave_merge$state_name == "South Carolina"] <- cat_list[6]
slave_merge$propbin[slave_merge$full_name == "St. David Parish (superseded)" & slave_merge$state_name == "South Carolina"] <- cat_list[6]
slave_merge$propbin[slave_merge$full_name == "Orange Parish (superseded)" & slave_merge$state_name == "South Carolina"] <- cat_list[6]
slave_merge$propbin[slave_merge$full_name == "Lancaster District" & slave_merge$state_name == "South Carolina"] <- cat_list[5]
slave_merge$propbin[slave_merge$full_name == "York District" & slave_merge$state_name == "South Carolina"] <- cat_list[5]
slave_merge$propbin[slave_merge$full_name == "Chester District" & slave_merge$state_name == "South Carolina"] <- cat_list[6]
slave_merge$propbin[slave_merge$full_name == "Fairfield District" & slave_merge$state_name == "South Carolina"] <- cat_list[6]
slave_merge$propbin[slave_merge$full_name == "Union District" & slave_merge$state_name == "South Carolina"] <- cat_list[6]
slave_merge$propbin[slave_merge$full_name == "Spartanburg District" & slave_merge$state_name == "South Carolina"] <- cat_list[4]
slave_merge$propbin[slave_merge$full_name == "Greenville District" & slave_merge$state_name == "South Carolina"] <- cat_list[4]
slave_merge$propbin[slave_merge$full_name == "Pickens District" & slave_merge$state_name == "South Carolina"] <- cat_list[4]
slave_merge$propbin[slave_merge$full_name == "Anderson District" & slave_merge$state_name == "South Carolina"] <- cat_list[5]
slave_merge$propbin[slave_merge$full_name == "Laurens District" & slave_merge$state_name == "South Carolina"] <- cat_list[6]
slave_merge$propbin[slave_merge$full_name == "Abbeville District" & slave_merge$state_name == "South Carolina"] <- cat_list[5]
slave_merge$propbin[slave_merge$full_name == "Edgefield District" & slave_merge$state_name == "South Carolina"] <- cat_list[5]
slave_merge$propbin[slave_merge$full_name == "Newberry District" & slave_merge$state_name == "South Carolina"] <- cat_list[5]
slave_merge$propbin[slave_merge$full_name == "Sumter District" & slave_merge$state_name == "South Carolina"] <- cat_list[6]
slave_merge$propbin[slave_merge$full_name == "Richland District" & slave_merge$state_name == "South Carolina"] <- cat_list[5]
slave_merge$propbin[slave_merge$full_name == "Prince George-Winyaw Parish (superseded)" & slave_merge$state_name == "South Carolina"] <- cat_list[5]

slave_merge$propbin[slave_merge$full_name == "Indian Territory" & slave_merge$state_name == "Oklahoma"] <- cat_list[2]
slave_merge$propbin[slave_merge$full_name == "GREER" & slave_merge$state_name == "Oklahoma"] <- cat_list[2]

slave_merge$propbin[slave_merge$full_name == "CARROLL (extinct)" & slave_merge$state_name == "Louisiana"] <- cat_list[7]

### Make Map

leaflet(options = leafletOptions(minZoom = 3, maxZoom = 6))
deteup <- paste0("<B>County: ",lynchings$county, " - </B>", lynchings$vic_detes)
popup <- paste0("<B>County: ",slave_merge$full_name, " - </B> State: ",slave_merge$state_name)
binpal <- colorFactor(c("white", "#cecddb", "#9d9bb8", "#6d6994", "#3c3771", "#0a0546"), na.color = "white", domain = slave_merge$propbin)
dot_map <- leaflet() %>%
  addProviderTiles("CartoDB.Positron") %>%
  addPolygons(data = slave_merge,
              stroke = TRUE,
              opacity=.15,
              color="grey", 
              fillColor = ~binpal(slave_merge$propbin), # you need to use hex colors
              fillOpacity = .7, 
              weight = .5, 
              smoothFactor = 0.2
  ) %>%  
  
  addPolylines(data = slave_merge,                  
               stroke = TRUE,
               weight = .5,
               color="grey") %>%
  
  addCircleMarkers(lng = lynchings$long_jit, lat = lynchings$lat_jit, weight=7, opacity = .1, radius =1.5, 
                   color=lynchings$colors, stroke = TRUE, fillOpacity = .6, popup = deteup
  ) %>%
  
  addLegend( 
    colors =  c("white", "#e6e6ec", "#b5b4c7", "#8482a2", "#53507d", "#221d58", "#080438"),
    #labels = c("0", "1-325", "326-1278", "1279-2868", "2869-6033", "6034-8940", "8941-37290"),
    labels = c("0", "0.01-0.06", "0.06-0.16", "0.17-0.32", "0.33-0.49", "0.50-0.60", "0.60-0.93"),
    position = "bottomright", 
    title = "Proportion Enslaved by County (1860 Census)  <br />  •Each Dot Represents 1 Black Lynching Victim")

dot_map
  
slave_lynch_dot <- setView(dot_map, lat = 39, lng = -97, zoom = 5)
```


Column
-----------------

###

```{r}
slave_lynch_dot
```


More Student Research {data-icon="fa-map"}
===========================================================

```{r, include=FALSE}

         
data_ts <- read.csv("https://davidrigbysociology.s3.amazonaws.com/lynching_data/data_for_execution_lynching_map.csv")
data_ts$GEOID <- sprintf("%05s",data_ts$GEOID)

dot_data <- read.csv("https://davidrigbysociology.s3.amazonaws.com/lynching_data/make_dot_map_with_this_03.csv", colClasses='character', stringsAsFactors=F)
dot_data$verified <- as.numeric(dot_data$verified)
lynching_info <- subset(dot_data, race_count=="Black") %>%
                 select(GEOID, vic_detes, verified) 

lynching_info <- lynching_info %>% group_by(GEOID) %>%
                 mutate(Black_Lynching_Count = sum(verified),
                        County_Lynch_List    = paste0(vic_detes,collapse = " </br>")) %>%
                 select(-c(verified,vic_detes))

lynching_info <- lynching_info[!duplicated(lynching_info$GEOID),]

          mapdata <- left_join(data_ts, lynching_info, by = "GEOID", copy = FALSE)

          mapdata$Black_Lynching_Count[is.na(mapdata$Black_Lynching_Count)]<-0

          mapdata$Weighted_EnslavedCount_1860 <- as.numeric(mapdata$Weighted_EnslavedCount_1860)
          mapdata$Weighted_EnslavedCount_1860 [is.na(mapdata$Weighted_EnslavedCount_1860)] <- 0

          mapdata$Weighted_TotPop_1860 <- as.numeric(mapdata$Weighted_TotPop_1860)
          mapdata$Weighted_TotPop_1860[is.na(mapdata$Weighted_TotPop_1860)] <- 0
          
          
          mapdata$State_Fips_2017 <- sprintf("%02s",data_ts$State_Fips_2017)
          mapdata$slave_state = 0
          mapdata$slave_state[mapdata$State_Fips_2017=="48"|mapdata$State_Fips_2017=="22"|mapdata$State_Fips_2017=="01"|
                                mapdata$State_Fips_2017=="28"|mapdata$State_Fips_2017=="29"|mapdata$State_Fips_2017=="05"|
                                mapdata$State_Fips_2017=="40"|mapdata$State_Fips_2017=="13"|mapdata$State_Fips_2017=="12"|
                                mapdata$State_Fips_2017=="45"|mapdata$State_Fips_2017=="37"|mapdata$State_Fips_2017=="51"|
                                mapdata$State_Fips_2017=="54"|mapdata$State_Fips_2017=="10"|mapdata$State_Fips_2017=="24"|
                                mapdata$State_Fips_2017=="47"|mapdata$State_Fips_2017=="21"] <- 1

          mapdata$slave_prop <- mapdata$Weighted_EnslavedCount_1860/mapdata$Weighted_TotPop_1860

          
          mapdata$slave_prop[mapdata$State_2017=="New Jersey"|mapdata$State_2017=="Kansas"|mapdata$State_2017=="Nebraska"|
                             mapdata$State_2017=="Pennsylvania"|mapdata$State_2017=="New York"|mapdata$State_2017=="New Mexico"|
                             mapdata$State_2017=="Illinois"] <- 0
          
          mapdata$slave_prop[mapdata$State_2017=="Maryland" & mapdata$County_2017=="Washington"]        <- 0.04567591
          mapdata$slave_prop[mapdata$State_2017=="Maryland" & mapdata$County_2017=="Montgomery"]        <- 0.2958738
          mapdata$slave_prop[mapdata$State_2017=="Maryland" & mapdata$County_2017=="Montgomery"]        <- 0.2958738
          mapdata$slave_prop[mapdata$State_2017=="Maryland" & mapdata$County_2017=="Prince George's"]   <- 0.5349595
          mapdata$slave_prop[mapdata$State_2017=="Maryland" & mapdata$County_2017=="Washington"]        <- 0.04567591
          mapdata$slave_prop[mapdata$State_2017=="Texas"    & mapdata$County_2017=="Jack"]              <- 0.05
          mapdata$slave_prop[mapdata$State_2017=="Texas"    & mapdata$County_2017=="Montague"]          <- 0.04122497
          mapdata$slave_prop[mapdata$State_2017=="Texas"    & mapdata$County_2017=="Cooke"]             <- 0.0981383
          mapdata$slave_prop[mapdata$State_2017=="Texas"    & mapdata$County_2017=="Grayson"]           <- 0.157869
          mapdata$slave_prop[mapdata$State_2017=="Texas"    & mapdata$County_2017=="Fannin"]            <- 0.1867202
          mapdata$slave_prop[mapdata$State_2017=="Texas"    & mapdata$County_2017=="Lamar"]             <- 0.2794988
          mapdata$slave_prop[mapdata$State_2017=="Texas"    & mapdata$County_2017=="Red River"]         <- 0.3560633
          mapdata$slave_prop[mapdata$State_2017=="Texas"    & mapdata$County_2017=="Bowie"]             <- 0.5247427
          mapdata$slave_prop[mapdata$State_2017=="Arkansas" & mapdata$County_2017=="Sevier"]            <- 0.3200837
          mapdata$slave_prop[mapdata$State_2017=="Arkansas" & mapdata$County_2017=="Polk"]              <- 0.04035664
          mapdata$slave_prop[mapdata$State_2017=="Arkansas" & mapdata$County_2017=="Scott"]             <- 0.04178814
          mapdata$slave_prop[mapdata$State_2017=="Arkansas" & mapdata$County_2017=="Sebastian"]         <- 0.07360901
          mapdata$slave_prop[mapdata$State_2017=="Arkansas" & mapdata$County_2017=="Crawford"]          <- 0.1092994
          mapdata$slave_prop[mapdata$State_2017=="Arkansas" & mapdata$County_2017=="Washington"]        <- 0.1017515
          mapdata$slave_prop[mapdata$State_2017=="Arkansas" & mapdata$County_2017=="Benton"]            <- 0.0412637
          mapdata$slave_prop[mapdata$State_2017=="Arkansas" & mapdata$County_2017=="Little River"]      <-  0.3200837
          mapdata$slave_prop[mapdata$State_2017=="Missouri" & mapdata$County_2017=="McDonald"]          <- 0.01783061
          mapdata$slave_prop[mapdata$State_2017=="Missouri" & mapdata$County_2017=="Newton"]            <- 0.04571306
          
          
          cat_list <- c("0", 				
                        "0-0.0631", 		
                        "0.06311-0.1666", 	
                        "0.16661-0.3221", 	
                        "0.32211-0.4957", 	
                        "0.49571-0.601", 	
                        "0.6011-0.925")

          
          mapdata$propbin <- "0"
          mapdata$propbin[mapdata$slave_prop > 0      & mapdata$slave_prop <= 0.0631] <- cat_list[2]
          mapdata$propbin[mapdata$slave_prop > 0.0631 & mapdata$slave_prop <= 0.1666] <- cat_list[3]
          mapdata$propbin[mapdata$slave_prop > 0.1666 & mapdata$slave_prop <= 0.3221] <- cat_list[4]
          mapdata$propbin[mapdata$slave_prop > 0.3221 & mapdata$slave_prop <= 0.4957] <- cat_list[5]
          mapdata$propbin[mapdata$slave_prop > 0.4957 & mapdata$slave_prop <= 0.601] <- cat_list[6]
          mapdata$propbin[mapdata$slave_prop > 0.6011 & mapdata$slave_prop <= 0.925] <- cat_list[7]

          mapdata$propbin[mapdata$County_2017=="Little River" & mapdata$State_2017=="Arkansas"]

          
          mapdata$propbin[mapdata$State_2017 == "Oklahoma"] <- cat_list[2]
          

          ### Colorcode Lynchings and Executions
          color_lynch <- c('0' = 'none', '1'= "#D4820F")
          color_execution <- c('0' = 'none', '1' = "#8b0000")
          
          mapdata$execution_colorcode <- 0

          mapdata$execution_colorcode[mapdata$Black_Execution_Count >= 1] <- "#8b0000"
          mapdata$execution_colorcode[mapdata$Black_Execution_Count < 1] <- "none"
          
          mapdata$lynching_colorcode <- 'none'

          mapdata$lynching_colorcode[mapdata$Black_Lynching_Count >= 1] <- "#D4820F"

          
          ### Coordinates for CircleMarkers
          sl <- unique(mapdata$State_Fips_2017[mapdata$State_Fips_2017!="72"])

          invisible(capture.output(us_county_shape <- counties(sl, cb = TRUE, year = NULL)))
          cds <- coordinates(us_county_shape)
          dot_coords <- cbind(as.data.frame(cds) %>% setNames(c("long","lat")),us_county_shape@data["GEOID"])
          mapdata <- sp::merge(mapdata,dot_coords, by = "GEOID")
          mapdata <- sp::merge(us_county_shape,mapdata, by = "GEOID", duplicateGeoms = TRUE)

          mapdata$Black_Lynching_Count[is.na(mapdata$Black_Lynching_Count)] <- 0
          mapdata$slave_prop[is.na(mapdata$slave_prop)] <- 0

          mapdata$long_lynch <- jitter(mapdata$long, factor = 50)
          mapdata$lat_lynch <- jitter(mapdata$lat, factor = 50)
          mapdata$long_ex <- jitter(mapdata$long, factor = 50)
          mapdata$lat_ex <- jitter(mapdata$lat, factor = 50)
          
          mapdata$County_Lynch_List[mapdata$County=="Duluth" & mapdata$State=="Minnesota"]

          
          ### MAKE MAP
          lynchup <- paste0("<B>Lynchings in ",mapdata$County, ", ", mapdata$State,"</B> </br>", mapdata$County_Lynch_List)
          exup    <- paste0("<B>Executions in ",mapdata$County, ", ", mapdata$State,"</B> </br>", mapdata$County_Ex_List)
          popup   <- paste0("<B> County: ",mapdata$County_1990, ", ", mapdata$State_2017, ":</br>",
                          "Prop. Enslaved 1860: ", round(mapdata$slave_prop, digits=3))
          binpal <- colorFactor(c("white", "#cecddb", "#9d9bb8", "#6d6994", "#3c3771", "#0a0546"), na.color = "white", domain = mapdata$propbin)
          
          dot_map <- leaflet(mapdata) %>%
            addProviderTiles("CartoDB.Positron") %>%
            addPolygons(data = mapdata,
                        stroke = TRUE,
                        opacity=.15,
                        color="grey", 
                        fillColor = ~binpal(mapdata$propbin), # you need to use hex colors
                        fillOpacity = .7, 
                        weight = .5, 
                        smoothFactor = 0.2,
                        popup = popup,               
                        highlightOptions = highlightOptions(color = "black", weight = 1, opacity = 2,
                                                            bringToFront = TRUE)) %>%
            
            addPolylines(data = mapdata,                  
                         stroke = TRUE,
                         weight = .5,
                         color="grey") %>%
            
            addCircleMarkers(lng = mapdata$long_ex, lat = mapdata$lat_ex, 
                             radius = ~ 5*log(1+(1.5*Black_Execution_Count)), weight=1, opacity = .4,
                             color= mapdata$execution_colorcode, stroke = TRUE, fillOpacity = .4, popup = exup) %>%
            
            addCircleMarkers(lng = mapdata$long_lynch, lat = mapdata$lat_lynch, 
                             radius = ~ 5*log(1+(Black_Lynching_Count/4)), weight=1, opacity = .4,
                             color= mapdata$lynching_colorcode, stroke = TRUE, fillOpacity = .4, popup = lynchup) %>%
            
            addLegend( 
              colors =  c("white", "#e6e6ec", "#b5b4c7", "#8482a2", "#53507d", "#221d58", "#080438"),
              labels = c("0", "0.01-0.06", "0.06-0.16", "0.17-0.32", "0.33-0.49", "0.50-0.60", "0.60-0.93"),
              position = "bottomright", 
              title = "Proportion Enslaved by County (1860 Census)") %>%
            
            addLegend( 
              colors =  c("#D4820F", "#580000"),
              labels = c("Lynching", "Execution"),
              position = "bottomleft",
              title = "Lynchings and Legal Executions in the US") 
          

          lynch_execution_map <- setView(dot_map,lat = 39, lng = -97, zoom = 5)
```


Column
-----------------

###

```{r}
lynch_execution_map
```


